version: '3.8'

services:
  directus:
    image: directus/directus:11.1.1
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      # Security - make this VERY long and random
      SECRET: "your-super-long-random-secret-replace-this-with-keyboard-smashing"
      
      # Your admin login credentials (YOU choose these!)
      ADMIN_EMAIL: "mike@frigger.com.au"
      ADMIN_PASSWORD: "398fnpdfn93qnfkjlnf9affu39hjn"
      
      # Connect to your NEW PostgreSQL database (same as your website uses)
      DB_CLIENT: "pg"
      DB_CONNECTION_STRING: "postgresql://neondb_owner:npg_WTbN41kEoBVL@ep-floral-star-a7altovh-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      
      # Allow your Next.js website to talk to Directus
      CORS_ENABLED: "true"
      CORS_ORIGIN: "https://www.cannaus.com.au/"
      
      # The URL where you'll access the admin panel
      PUBLIC_URL: "https://admin.cannaus.com.au/"
      
      # File storage settings
      STORAGE_LOCATIONS: "local"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "./uploads"